create table public.person_confessions (
  id bigint generated by default as identity not null,
  user_id uuid null,
  creator_id uuid not null,
  person_id uuid not null,
  person_name text null,
  content text null,
  media jsonb null,
  is_anonymous boolean null default true,
  likes_count integer null default 0,
  comments_count integer null default 0,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint person_confessions_pkey primary key (id),
  constraint person_confessions_creator_id_fkey foreign KEY (creator_id) references profiles (id) on delete CASCADE,
  constraint person_confessions_person_id_fkey foreign KEY (person_id) references person_profiles (id) on delete CASCADE,
  constraint person_confessions_user_id_fkey foreign KEY (user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;



Policies
Manage Row Level Security policies for your tables

Docs
106575

schema

public

person_confessions

Disable RLS

Create policy

Name	Command	Applied to	Actions

Authenticated users can create person confessions
INSERT	
public


Authenticated users can read person confessions
SELECT	
public


Creators can delete their own person confessions
DELETE	
public


Creators can update their own person confessions
UPDATE	
public

