create table public.person_profiles (
  id uuid not null default extensions.uuid_generate_v4 (),
  name text not null,
  profile_image text null,
  bio text null,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  updated_at timestamp with time zone null default timezone ('utc'::text, now()),
  created_by uuid null,
  constraint person_profiles_pkey primary key (id),
  constraint person_profiles_created_by_fkey foreign KEY (created_by) references auth.users (id) on delete set null
) TABLESPACE pg_default;


Policy Name
Authenticated users can create person profiles
Table

on clause


public.person_profiles
Policy Behavior

as clause

permissive
Policy Command

for clause



INSERT



Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Authenticated users can create person profiles"


on "public"."person_profiles"


to public


with check (

  (auth.uid() = created_by)

);



Policy Name
Authenticated users can read person profiles
Table

on clause


public.person_profiles
Policy Behavior

as clause

permissive
Policy Command

for clause


SELECT


Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Authenticated users can read person profiles"


on "public"."person_profiles"


to public


using (


  (auth.role() = 'authenticated'::text)

);



Policy Name
Authenticated users can update person profiles
Table

on clause


public.person_profiles
Policy Behavior

as clause

permissive
Policy Command

for clause


SELECT

INSERT

UPDATE

DELETE

ALL
Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Authenticated users can update person profiles"


on "public"."person_profiles"


to public


using (


  (auth.role() = 'authenticated'::text)

with check (


  true

);


Policy Name
Creators can delete their own person profiles
Table

on clause


public.person_profiles
Policy Behavior

as clause

permissive
Policy Command

for clause




DELETE

Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Creators can delete their own person profiles"


on "public"."person_profiles"


to public


using (


  (auth.uid() = created_by)

);





create table public.person_confessions (
  id bigint generated by default as identity not null,
  user_id uuid null,
  creator_id uuid not null,
  person_id uuid not null,
  person_name text null,
  content text null,
  media jsonb null,
  is_anonymous boolean null default true,
  likes_count integer null default 0,
  comments_count integer null default 0,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint person_confessions_pkey primary key (id),
  constraint person_confessions_creator_id_fkey foreign KEY (creator_id) references profiles (id) on delete CASCADE,
  constraint person_confessions_person_id_fkey foreign KEY (person_id) references person_profiles (id) on delete CASCADE,
  constraint person_confessions_user_id_fkey foreign KEY (user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;




Policy Name
Authenticated users can create person confessions
Table

on clause


public.person_confessions
Policy Behavior

as clause

permissive
Policy Command

for clause




INSERT


Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Authenticated users can create person confessions"


on "public"."person_confessions"


to public


with check (

7
  (auth.uid() = creator_id)

);



Policy Name
Authenticated users can read person confessions
Table

on clause


public.person_confessions
Policy Behavior

as clause

permissive
Policy Command

for clause


SELECT


Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Authenticated users can read person confessions"


on "public"."person_confessions"


to public


using (


  true

);



Policy Name
Creators can delete their own person confessions
Table

on clause


public.person_confessions
Policy Behavior

as clause

permissive
Policy Command

for clause



DELETE


Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Creators can delete their own person confessions"


on "public"."person_confessions"


to public


using (


  (auth.uid() = creator_id)

);



Policy Name
Creators can update their own person confessions
Table

on clause


public.person_confessions
Policy Behavior

as clause

permissive
Policy Command

for clause




UPDATE


Target Roles

to clause

Defaults to all (public) roles if none selected
Use options above to edit


alter policy "Creators can update their own person confessions"


on "public"."person_confessions"


to public


using (

7
  (auth.uid() = creator_id)

with check (

  (auth.ui

);